### ISSUE TITLE
lexical error: invalid char in json text

### ISSUE THREAD

**Issue by margulesgroome** [swop-cx/swop#1]
Hi, as of about 18 Sept we receive this following error message when retrieving data via the swop.cx API:

Error: lexical error: invalid char in json text.
                                       <html>  <head><title>504 Gatewa
                     (right here) ------^

Code has been running for ~2 years without issues so unsure if something changed on the API side ? Any help will be appreciated. Thank you

**Comment by jadlr** [comment]
Hi @margulesgroome can you give us details about what endpoint you're calling?

**Comment by margulesgroome** [comment]
Hi

Can you please clarify what you mean with endpoint ?

Thank you
Rudolf


Margules Groome Consulting Pty Ltd
Scottish House
Level 4, 90 William St
Melbourne, VIC, 3000, AUSTRALIA
Tel: +61 3 8199 7937
Mobile: +61 (0) 400 144 742
Skype: rudolf_van_rensburg

***@***.***<http://www.margulesgroome.com/>

**Comment by jadlr** [comment]
Hi Rudolf, are you using the REST or the GraphQL API? Can you give me details about the request/query you're executing? Thanks!

**Comment by margulesgroome** [comment]
Hi,

We are using an R environment to call the swop API. Below the code we are using. As indicated this code has been running well for ~2 years but stopped working on 18 Sept.


CurrencyList <- c('AUD','BRL','CLP','CNY','EUR','GBP','JPY','MYR','NZD','UYU','VND','ZAR')  # List of quote currencies


  ResultDF<- data.frame() # empty dataframe as output holder


  # Now adjusted to make the date range dynamic for each currency
  for(i in 1:length(CurrencyList)) # loop 1
  {

    LastAvailableFXDate  <- sqlQuery(ch,paste("SELECT MAX(quote_date) AS LastAvailableFXDate FROM forex.daily_fx WHERE forecast = 0 and quote_currency = '", CurrencyList[i], "'", sep=''))
    StartFXQueryDate <- as.Date(LastAvailableFXDate[1,1],format="%Y-%m-%d")+1

    DateList <- seq(StartFXQueryDate, MaxQueryDate, by = "days") # List of dates


    for(h in 1:length(DateList)) # loop 2
    {
     APIQuery <- paste(https://swop.cx/rest/rates?date=,DateList[h],"&base_currency=USD&quote_currencies=", CurrencyList[i], sep='')
     #print(APIQuery)
     result <- GET(APIQuery,add_headers(Authorization = paste("ApiKey", apiKey)))
     jsonResponseText <- content(result,"text", encoding = "ISO-8859-1")
     Data = fromJSON(jsonResponseText)
     ResultDF<-bind_rows(ResultDF, Data)


Regard
Rudolf

**Comment by jadlr** [comment]
I just tried the request and it works fine. I also checked our logs and couldn't find our service responding with a 504. Could it be that something in you network changed. 504 indicates a gateway timeout. This could come from a firewall or proxy. 

We didn't deploy any changes around the 18th of Sept.

**Comment by margulesgroome** [comment]
Jonas

Thank you – we think we just found the issue, a change of directory structure on our server that was caused by 3rd party software.

Thank you for your prompt responses and willingness to assist.

Best regards
Rudolf

**Comment by jadlr** [comment]
You're very welcome, Rudolf! I'll close this issue for now, let me know if you run into any other issues.
